<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Поиск");

$APPLICATION->IncludeComponent(
	"bitrix:catalog.search",
	"cn",
	array(
		"SHOW_CATALOG_QUANTITY_CNT" => "N",
		"SHOW_CATALOG_QUANTITY" => "N",
		"QTY_SHOW_TYPE" => "NUM",
		"IN_STOCK" => "В наличии",
		"NOT_IN_STOCK" => "Нет в наличии",
		"QTY_MANY_GOODS_INT" => "3",
		"QTY_MANY_GOODS_TEXT" => "много",
		"QTY_LESS_GOODS_TEXT" => "мало",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "12",
		"ELEMENT_SORT_FIELD" => ["PROPERTYSORT_SALELEADER","PROPERTY_MINIMUM_PRICE"],
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_FIELD2" => "shows",
		"ELEMENT_SORT_ORDER2" => "asc",
		"PAGE_ELEMENT_COUNT" => "36",
		"LINE_ELEMENT_COUNT" => "3",
		"PROPERTY_CODE" => [],
		"OFFERS_CART_PROPERTIES" => ["SIZE"],
		"OFFERS_FIELD_CODE" => ["NAME"],
		"OFFERS_PROPERTY_CODE" => [],
		"OFFERS_SORT_FIELD" => "shows",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "shows",
		"OFFERS_SORT_ORDER2" => "asc",
		"OFFERS_LIMIT" => "5",
		"SECTION_URL" => "#SECTION_CODE#/",
		"DETAIL_URL" => "#SECTION_CODE#/#ELEMENT_CODE#",
		"BASKET_URL" => "/personal/basket/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"SECTION_ID_VARIABLE" => "SECTION_CODE",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600000",
		'DISPLAY_COMPARE' => "Y",
		"PRICE_CODE" => ["BASE"],
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => false,
		"PRICE_VAT_INCLUDE" => "Y",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRODUCT_PROPERTIES" => "",
		"USE_PRODUCT_QUANTITY" => "Y",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "RUB",
		'HIDE_NOT_AVAILABLE' => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "0",
		"PAGER_SHOW_ALL" => "N",
		"FILTER_NAME" => "searchFilter",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"SECTION_USER_FIELDS" => array(),
		"INCLUDE_SUBSECTIONS" => "Y",
		"SHOW_ALL_WO_SECTION" => "Y",
		"META_KEYWORDS" => "",
		"META_DESCRIPTION" => "",
		"BROWSER_TITLE" => "",
		"ADD_SECTIONS_CHAIN" => "N",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",

		"RESTART" => "N",
		"NO_WORD_LOGIC" => "N",
		"USE_LANGUAGE_GUESS" => "N",
		"CHECK_DATES" => "N",

		'LABEL_PROP' => "-",
		'ADD_PICT_PROP' => "MORE_PHOTO",
		'PRODUCT_DISPLAY_MODE' => "Y",

		'OFFER_ADD_PICT_PROP' => "-",
		'OFFER_TREE_PROPS' => "",
		'PRODUCT_SUBSCRIPTION' => "N",
		'SHOW_DISCOUNT_PERCENT' => "Y",
		'SHOW_OLD_PRICE' => "Y",
		'MESS_BTN_BUY' => "Купить",
		'MESS_BTN_ADD_TO_BASKET' => "В корзину",
		'MESS_BTN_SUBSCRIBE' => "",
		'MESS_BTN_DETAIL' => "Подробнее",
		'MESS_NOT_AVAILABLE' => "Нет в наличии",

		'TEMPLATE_THEME' => "site",
		'ADD_TO_BASKET_ACTION' => "BUY",
		'SHOW_CLOSE_POPUP' => "N",
		'COMPARE_PATH' => "/catalog/compare.php?action=#ACTION_CODE#",
		"TILE_SHOW_PROPERTIES" => "N"
	)
);
/*
$APPLICATION->IncludeComponent(
	"bitrix:search.page",
	"",
	Array(
		"RESTART" => "N",
		"NO_WORD_LOGIC" => "N",
		"CHECK_DATES" => "N",
		"USE_TITLE_RANK" => "N",
		"DEFAULT_SORT" => "rank",
		"FILTER_NAME" => "",
		"arrFILTER" => array(),
		"SHOW_WHERE" => "Y",
		"arrWHERE" => array(),
		"SHOW_WHEN" => "N",
		"PAGE_RESULT_COUNT" => "50",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600",
		"USE_LANGUAGE_GUESS" => "N",
		"USE_SUGGEST" => "N",
		"DISPLAY_TOP_PAGER" => "Y",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Результаты поиска",
		"PAGER_SHOW_ALWAYS" => "Y",
		"PAGER_TEMPLATE" => ""
	)
);
*/

require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");